### PR TITLE
Resolving compilation issues, adding data generator, and integrating w/ CI

### LINKED ISSUE #12: Data Generator - logbook
# Introduction
This issue will serve as a simple logbook for creating the MVP data generator. 

# The Goals
The goal is to write a program that
1. generates some static XiaData classes.
2. writes those data to a PLD and an LDF

# Setup 
Here are the values that are hard coded into the generator. 
```c++
    const unsigned int channelNumber = 0;
    vector<unsigned int> encodedData;
    const unsigned int energy = 55;
    const string firmware = "30474";
    const unsigned int frequency = 250;
    const unsigned int ldfFormatCode = 0;
    const unsigned int moduleNumber = 0;
    const unsigned int numberOfDataWords = 4;
    const unsigned int numberOfDataBuffers = 2;
    const string outputName = "dataGeneratorTest";
    const string outputPath = "/tmp/";
    const unsigned int pldFormatCode = 1;
    const unsigned int slotNumber = moduleNumber + 2;
    unsigned int runNumber = 0;
    const string runTitle = "Constant Data with Energy = 55, Mod=Chan=Crate=0";
    const unsigned int totalNumberOfWords = 6;
```

# Notes
1. The MVP for this will NOT randomly generate anything. Everything will be static. This provides easier debugging. 
2. The data files will be output to `/tmp` since they can be regenerated at any time and do not need to be stored long term.
3. The program generates both an LDF and a PLD.

### LINKED ISSUE #17: Fix equality checking for XiaData
There are times when the values checked for equality with XiaData are true values. We check that IDs and times are not equal to the defaults of 0. It *is* possible to have an XiaData event with an ID of 0 and a time of 0.

### LINKED ISSUE #23: Error compiling Correlator w/ utkscan
@jjvz reported having an issue compiling Correlator.
```c++
/opt/paass/Analysis/Utkscan/core/source/Correlator.cpp:200:32: error: call of overloaded ‘isnan(double&)’ is ambiguous
             if (!isnan(lastTime)) {
```

I still think it's weird that these types of issues are caught by some compilers and not caught by others.

### LINKED ISSUE #24: Utkscan fails to compile when all the Utkscan flags are toggled on
@jjvs has reported an issue when trying to compile `utkscan` with all of the flags toggled ON. 
image

# The error message
```c++
/opt/paass/Analysis/Utkscan/processors/source/CloverProcessor.cpp:101:34: error: ‘class Globals’ has no member named ‘configfile’
     string cfg = Globals::get()->configfile();
                                  ^
/opt/paass/Analysis/Utkscan/processors/source/CloverProcessor.cpp:130:17: error: ‘GeneralException’ was not declared in this scope
 not implemented");
                 ^
/opt/paass/Analysis/Utkscan/processors/source/CloverProcessor.cpp: In member function ‘virtual bool CloverProcessor::Process(RawEvent&)’:
/opt/paass/Analysis/Utkscan/processors/source/CloverProcessor.cpp:712:51: error: ‘class ChanEvent’ has no member named ‘GetCalEnergy’
                         double gEnergy3 = (*it3)->GetCalEnergy();
```

### LINKED ISSUE #25: Get this rascal running on a CI server
For now we're going w/ TravisCI. Ideally, I'd like a Jenkins server, but I don't have a good place to host that ATM.

### LINKED ISSUE #30: Fix TravisCI so that it compiles the proper version of the code.
Right now we've got it setup so that it pulls the repo from scratch. TravisCI does that before we begin the build process : 

```
0.83s$ git clone --depth=50 --branch=dev https://github.com/spaulaus/paass-laughing-conqueror.git spaulaus/paass-laughing-conqueror
Cloning into 'spaulaus/paass-laughing-conqueror'...
remote: Counting objects: 1748, done.
remote: Compressing objects:remote: Compressing objects: 100% (876/876), done.
remote: Total 1748 (delta 941), reused 1342 (delta 824), pack-reused 0
Receiving objects: 100% (1748/1748), 1.15 MiB | 10.55 MiB/s, done.
Resolving deltas: 100% (941/941), done.
$ cd spaulaus/paass-laughing-conqueror
$ git checkout -qf f8d6d2d019b85f19424d0b5f5541dc967c9ca8e2
```
We do this again in the configuration, but only build off the master branch. This means that dev isn't testing stuff on dev.

### LINKED ISSUE #31: Update BitMasks
From Hui:

​Firmware version 34689 ​(RevF 14-bit, 100 MS/s, no source changes from 34688) should have the same header structure as 34688 (source files changed for all variants). However, ​34455 (RevF 14-bit, 250 MS/s)  has slightly different header structure than 34688 and later versions. 

34688
image

​34455
image

​The change made in 34688 was to accommodate the ​the 16-bit energy values available in the 16-bit variant of RevF.

### LINKED ISSUE #32: Clean up warning in TemplateExpProcessor.cpp:154
```
/home/travis/build/spaulaus/paass-laughing-conqueror/Analysis/Utkscan/experiment/source/TemplateExpProcessor.cpp: In member function ‘virtual bool TemplateExpProcessor::Process(RawEvent&)’:
/home/travis/build/spaulaus/paass-laughing-conqueror/Analysis/Utkscan/experiment/source/TemplateExpProcessor.cpp:154:20: warning: unused variable ‘gTime’ [-Wunused-variable]
             double gTime = chan->GetWalkCorrectedTime();
```

### LINKED ISSUE #33: Update travis.yml so that it runs unittests
Need to have the CI run unittests for us.

### LINKED ISSUE #35: Fix failing unittest
```
/home/travis/build/spaulaus/paass-laughing-conqueror/paass-laughing-conqueror/Analysis/ScanLibraries/tests/unittest-XiaListModeDataEncoder.cpp:27:1: error: Failure in TestEncoding: Expected exception: "invalid_argument" not thrown
FAILURE: 1 out of 2 tests failed (1 failures).
Test time: 0.00 seconds.
```

### LINKED ISSUE #36: Rename XiaData::Clear to XiaData::Initialize
The new method name is much clearer in function.

### PR DESCRIPTION
**Pull request by spaulaus**
Release notes: 

- Resolves #12 - Adds the data generator MVP. 
- Resolves #17 - This was fixed as part of #35.
- Resolves #24 - Fixes compilation issues in CloverProcessor and ImplantSsdProcessor when all utkscan flags are toggled ON
- Resolves #25 - We are not integrated with TravisCI. The build status is shown next to the commit ID. 
- Resolves #23 - Fixes isnan errors found during compilation on iThemba and CI machines.
- Resolves #30 - We are now compiling against the correct commit. I've also setup integration w/ Slack.
- Resolves #31 - Updated the logic in `XiaListModeDataMask::ConvertStringToFirmware` 
- Resolves #32 - Fixes warnings in TemplateExpProcessor.cpp and HistScannerChanData.cpp
- Resolves #33 - Now running the unittests, which exposed #35 . 
- Resolves #35 - unittest-XiaListModeDataEncoder no longer dies due to a bad XiaData Init.
- Resolves #36 - Renames Clear method of XiaData

### CODE REVIEW

**Comment by ksmith0** [comment]
Comment one: pull request name is not descriptive.

**Comment by spaulaus** [comment]
> Comment one: pull request name is not descriptive.

Let me fix that.

File: Acquisition/Utilities/DataGenerator/source/dataGenerator.cpp [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+///@copyright All rights reserved. Released under the Creative Commons Attribution-ShareAlike 4.0 International License
+#include <array>
+#include <iostream>
+
+#include "XiaListModeDataEncoder.hpp"
+#include "hribf_buffers.h"
+
+using namespace std;
+
+int main(int argc, char *argv[]) {
```
Comment (ksmith0) [inline Acquisition/Utilities/DataGenerator/source/dataGenerator.cpp]: This is MVP correct? Otherwise it would be nice to take all these configuration variable as arguments.

File: Acquisition/Utilities/DataGenerator/test/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,4 @@
+#@author S. V. Paulauskas
+#add_executable(unittest-WalkCorrector unittest-WalkCorrector.cpp ../source/WalkCorrector.cpp)
+#target_link_libraries(unittest-WalkCorrector UnitTest++ ${LIBS})
+#install(TARGETS unittest-WalkCorrector DESTINATION bin/unittests)
```
Comment (ksmith0) [inline Acquisition/Utilities/DataGenerator/test/CMakeLists.txt]: It's all comments?

File: Acquisition/Utilities/DataGenerator/source/dataGenerator.cpp (hunk 1 above)
Comment (spaulaus) [reply Acquisition/Utilities/DataGenerator/source/dataGenerator.cpp]: As mentioned, this is an MVP - minimum viable product. The MVP provides a base for further improvements, and constitutes a working piece of software. 

image

File: Analysis/ScanLibraries/source/XiaListModeDataMask.cpp [hunk 3]
```diff
@@ -37,14 +37,10 @@ FIRMWARE XiaListModeDataMask::ConvertStringToFirmware(const std::string &type) {
         firmware = R30980;
     else if (firmwareNumber >= 30981 && firmwareNumber < 34688)
         firmware = R30981;
-    else if (firmwareNumber ==
-             34688) //compare exactly here since nothing higher
+    else if (firmwareNumber >= 34688)
```
Comment (ksmith0) [inline Analysis/ScanLibraries/source/XiaListModeDataMask.cpp]: Wouldn't it be nice to have a warning if a firmware was specified that may be beyond the last known value?

File: Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp [hunk 4]
```diff
@@ -39,12 +39,10 @@ void HistScannerChanData::Set(XiaData *data) {
...
-
-    //baseline[mod][chan] = chEvent->CorrectBaseline();
-
-    //peakAdc[mod][chan] = chEvent->maximum;
-    //traceQdc[mod][chan] = chEvent->IntegratePulse(chEvent->max_index - 10,
-    //                                              chEvent->max_index + 15);
+    //@TODO ensure that these work properly
+    baseline[mod][chan] = chEvent->GetTrace().GetBaselineInfo().first;
+    peakAdc[mod][chan] = chEvent->GetTrace().GetMaxInfo().second;
+    traceQdc[mod][chan] = chEvent->GetTrace().GetQdc();
```
Comment (ksmith0) [inline Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp]: Can we open an issue and make sure these don't get forgotten?

File: Acquisition/Utilities/DataGenerator/source/dataGenerator.cpp (hunk 1 above)
Comment (ksmith0) [reply Acquisition/Utilities/DataGenerator/source/dataGenerator.cpp]: I think a floating face might be very happy with a single wheel.

File: Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp (hunk 4 above)
Comment (ksmith0) [reply Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp]: Never mind these are not what I thought they were (I thought it was cfd info).

File: Analysis/ScanLibraries/source/XiaListModeDataMask.cpp (hunk 3 above)
Comment (ksmith0) [reply Analysis/ScanLibraries/source/XiaListModeDataMask.cpp]: Opened issue #41.

Comment (spaulaus) [reply Analysis/ScanLibraries/source/XiaListModeDataMask.cpp]: Would it be nice? I guess so since I see the slack notification for the ticket. I think that it's a good call out.

File: Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp (hunk 4 above)
Comment (spaulaus) [reply Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp]: Sure you can!

File: Acquisition/Utilities/DataGenerator/test/CMakeLists.txt (hunk 2 above)
Comment (spaulaus) [reply Acquisition/Utilities/DataGenerator/test/CMakeLists.txt]: Let's put in ticket for it.

Comment (spaulaus) [reply Acquisition/Utilities/DataGenerator/test/CMakeLists.txt]: I'm not sure why that's not being built.

Comment (ksmith0) [reply Acquisition/Utilities/DataGenerator/test/CMakeLists.txt]: Issue opened to resolve #42.

Comment (spaulaus) [reply Acquisition/Utilities/DataGenerator/test/CMakeLists.txt]: More precisely, I opened #42 to resolve this issue.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#27
